//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public Nullable<long> ProductionLineID { get; set; }
        public Nullable<bool> SendOrderCode { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<bool> SendGari { get; set; }
        public Nullable<bool> SendDestinationOrder { get; set; }
    }
}
