//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductiveDetails
    {
        public long ID { get; set; }
        public long OrderCodeID { get; set; }
        public long PartID { get; set; }
        public bool IO { get; set; }
        public Nullable<long> FromOrderCodeID { get; set; }
        public Nullable<long> ToOrderCodeID { get; set; }
        public string BatchNumber { get; set; }
        public string FormoulaNumber { get; set; }
        public bool Waste { get; set; }
        public Nullable<long> LesionID { get; set; }
        public double Amount { get; set; }
        public Nullable<long> ProductiveRowDetails { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public byte[] Version { get; set; }
        public long OperatorID { get; set; }
        public Nullable<long> FromPartID { get; set; }
        public Nullable<long> ToPartID { get; set; }
        public Nullable<double> Amount1 { get; set; }
        public Nullable<long> ProductionLineID { get; set; }
        public string IP { get; set; }
    
        public virtual Lesion Lesion { get; set; }
        public virtual Part Part { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual ProductiveState ProductiveState { get; set; }
        public virtual Order Order { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
    }
}
