//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OrderSummery
    {
        public long OrderCode { get; set; }
        public Nullable<double> AmountOfProductive { get; set; }
        public Nullable<long> AmountOfProductive1 { get; set; }
        public Nullable<double> AmountWaste { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Amount1 { get; set; }
        public Nullable<double> RemainingAmount { get; set; }
        public Nullable<double> RemainingAmount1 { get; set; }
        public string StatusTitle { get; set; }
    }
}
