//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProductiveDetails_Index
    {
        public long OrderCodeID { get; set; }
        public string PartCode { get; set; }
        public string Name { get; set; }
        public string OperatorName { get; set; }
        public string IO { get; set; }
        public Nullable<long> FromOrderCodeID { get; set; }
        public Nullable<long> ToOrderCodeID { get; set; }
        public string BatchNumber { get; set; }
        public string FormoulaNumber { get; set; }
        public bool Waste { get; set; }
        public Nullable<long> LesionID { get; set; }
        public double Amount { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public long ID { get; set; }
        public long PartID { get; set; }
        public long OperatorID { get; set; }
        public bool IOo { get; set; }
        public string LesionsName { get; set; }
        public string WasteType { get; set; }
        public string AddDateShamsi { get; set; }
        public string ProductionLineName { get; set; }
        public long Expr2 { get; set; }
        public Nullable<double> Amount1 { get; set; }
    }
}
