//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Part_Index
    {
        public string Name { get; set; }
        public string LatinName { get; set; }
        public string PartCode { get; set; }
        public string WastePartCode { get; set; }
        public string WasteName { get; set; }
        public string NatureName { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string UnitName { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public long ID { get; set; }
    }
}
