//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Productive_Stoppages_Index
    {
        public long OrderCodeID { get; set; }
        public string StoppagesName { get; set; }
        public string OperatorName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public long ID { get; set; }
        public long StoppagesID { get; set; }
        public long OperatorID { get; set; }
        public Nullable<long> ProductionLineID { get; set; }
        public Nullable<long> PartID { get; set; }
        public string ProductionLineName { get; set; }
        public string Name { get; set; }
        public string PartCode { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Minutes { get; set; }
    }
}
