//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TowzinEntities1 : DbContext
    {
        public TowzinEntities1()
            : base("name=TowzinEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Frame> Frame { get; set; }
        public virtual DbSet<Lesion> Lesion { get; set; }
        public virtual DbSet<Nature> Nature { get; set; }
        public virtual DbSet<OrderPart> OrderPart { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<PartFrame> PartFrame { get; set; }
        public virtual DbSet<PartGroup> PartGroup { get; set; }
        public virtual DbSet<PartGroupMember> PartGroupMember { get; set; }
        public virtual DbSet<PartPackageDetail> PartPackageDetail { get; set; }
        public virtual DbSet<PartSpecification> PartSpecification { get; set; }
        public virtual DbSet<ProductionLine> ProductionLine { get; set; }
        public virtual DbSet<ProductionLineTechnicalProblem> ProductionLineTechnicalProblem { get; set; }
        public virtual DbSet<ProductiveDetails> ProductiveDetails { get; set; }
        public virtual DbSet<ProductiveStoppages> ProductiveStoppages { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Stoppages> Stoppages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalProblem> TechnicalProblem { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Operator> Operator { get; set; }
        public virtual DbSet<VW_OrderPart_Index> VW_OrderPart_Index { get; set; }
        public virtual DbSet<ProductiveState> ProductiveState { get; set; }
        public virtual DbSet<VW_Part_Index> VW_Part_Index { get; set; }
        public virtual DbSet<VW_PartFrame_Index> VW_PartFrame_Index { get; set; }
        public virtual DbSet<VW_PartGroupMember_Index> VW_PartGroupMember_Index { get; set; }
        public virtual DbSet<VW_PartPackage_Index> VW_PartPackage_Index { get; set; }
        public virtual DbSet<VW_PartPackageDetail> VW_PartPackageDetail { get; set; }
        public virtual DbSet<VW_PartSpecification_Index> VW_PartSpecification_Index { get; set; }
        public virtual DbSet<VW_ProductionLineTechnicalProblem_Index> VW_ProductionLineTechnicalProblem_Index { get; set; }
        public virtual DbSet<VW_Productive_Stoppages_Index> VW_Productive_Stoppages_Index { get; set; }
        public virtual DbSet<VW_ProductiveDetails_Index> VW_ProductiveDetails_Index { get; set; }
        public virtual DbSet<PartPackage> PartPackage { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<VW_Order_Index> VW_Order_Index { get; set; }
    }
}
