//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Order_Index
    {
        public long OrderCode { get; set; }
        public string StatusTitle { get; set; }
        public string ProductionLineName { get; set; }
        public string FrameName { get; set; }
        public string FrameSerial { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<double> AmountOfProductive { get; set; }
        public Nullable<long> AmountOfSubUnitID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> WasteAmont { get; set; }
        public Nullable<double> RowMaterialAmont { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public long ID { get; set; }
    }
}
