//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Towzin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OrderPart_Index
    {
        public long OrderCodeID { get; set; }
        public string Name { get; set; }
        public string PartCode { get; set; }
        public string AmountOfProductive { get; set; }
        public string AmountOfSubUnit { get; set; }
        public string CustomerName { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public long ID { get; set; }
        public string Amount { get; set; }
        public string WasteAmount { get; set; }
        public string RowMaterialAmount { get; set; }
        public long PartID { get; set; }
        public string Creator { get; set; }
        public System.DateTime AddDate { get; set; }
        public string LastModifier { get; set; }
        public System.DateTime LastModificationDate { get; set; }
    }
}
